ALTER TABLE "Event" ADD COLUMN "category" TEXT;
ALTER TABLE "Event" ADD COLUMN "imageUrl" TEXT;
ALTER TABLE "Event" ADD COLUMN "isFeatured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Event" ADD COLUMN "isRegistrationOpen" BOOLEAN NOT NULL DEFAULT true;
